title: Site
pages: 
  template:
    - about
    - default
    - books
    - categories
    - authors
    - cities
    - countries
    - publishers
    - lexicon
    - symbols
    - search
fields:
  title:
    label: Title
    type:  text
  description:
    label: Description
    type:  textarea
  keywords:
    label: Keywords
    type:  tags
  email:
    label: Email
    type:  email
    width: 1/2
  soundcloud:
    label: SoundCloud
    type:  text
    icon: soundcloud
    width: 1/2
  twitter:
    label: Twitter
    type:  text
    help: Do not include '@'
    icon: twitter
    width: 1/2
  instagram:
    label: Instagram
    type:  text
    help: Do not include '@'
    icon: instagram
    width: 1/2
